### ISSUE TITLE
Duplicated door name on door Definition

### ISSUE THREAD

**Issue by baviera08** [osrf/romi-js-core-interfaces#5]
@koonpeng in this version "@osrf/romi-js-core-interfaces": "0.0.2-alpha.5", we have two values that I think there are referring to the same thing (the name of the door). If I'm right, which one should we keep? Can you delete one of those and publish a new version? 

``` typescript
name: string;
door_name: string;
```

Complete door definition

``` typescript
export declare class Door {
    name: string;
    door_name: string;
    v1_x: number;
    v1_y: number;
    v2_x: number;
    v2_y: number;
    door_type: number;
    motion_range: number;
    motion_direction: number;
    static readonly typeName = "building_map_msgs/msg/Door";
    static fromObject(obj: any): Door;
    static readonly DOOR_TYPE_UNDEFINED = 0;
    static readonly DOOR_TYPE_SINGLE_SLIDING = 1;
    static readonly DOOR_TYPE_DOUBLE_SLIDING = 2;
    static readonly DOOR_TYPE_SINGLE_TELESCOPE = 3;
    static readonly DOOR_TYPE_DOUBLE_TELESCOPE = 4;
    static readonly DOOR_TYPE_SINGLE_SWING = 5;
    static readonly DOOR_TYPE_DOUBLE_SWING = 6;
    constructor(name: string, door_name: string, v1_x: number, v1_y: number, v2_x: number, v2_y: number, door_type: number, motion_range: number, motion_direction: number);
}
```

**Comment by koonpeng** [comment]
good catch, the definitions are generated from ros. Looking at the definitions here does show there are `name` and `door_names` https://github.com/osrf/traffic_editor/blob/master/building_map_msgs/msg/Door.msg

maybe @Yadunund can help explain if this is a mistake or do they have different meaning?

**Comment by Yadunund** [comment]
Hi All,
I apologize for the duplicate name field in the Door msg definition. Kindly use `name` only. I will remove `door_name` from `building_map_msgs`. Also just a note, the building_map_server is currently publishing the location of doors and lifts in a non-SI coordinate system. So if you're seeing doors and lifts rendered at incorrect scales, I apologize for that as well. A fix for this is ready and I'll update again when it gets merged.

**Comment by baviera08** [comment]
Thanks @Yadunund , once this is addressed, would you let that know to @koonpeng so he can update the definitions of this project with a new release version? After this is done we can merge this https://github.com/osrf/romi-dashboard/pull/21 to master.

**Comment by baviera08** [comment]
Hi guys, do we have any updates on this issue?. I'm just asking to merge this https://github.com/osrf/romi-dashboard/pull/21 PR to master.

**Comment by Yadunund** [comment]
This [PR](https://github.com/osrf/traffic_editor/pull/131) is the intended fix. I'll follow up again with getting it reviewed/merged.

**Comment by Yadunund** [comment]
In the meanwhile, I think @koonpeng can update the definitions here to use `door`.

**Comment by koonpeng** [comment]
fixed
